services:

  postgres:
    image: postgres:15
    container_name: nyb_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5434:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      retries: 5

  airflow-init:
    image: apache/airflow:2.9.3
    container_name: nyb_airflow_init
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    volumes:
      - ./:/opt/airflow
    command: >
      bash -c "airflow db migrate &&
      airflow users create
      --username admin
      --password admin
      --firstname admin
      --lastname admin
      --role Admin
      --email admin@example.com"

  airflow-webserver:
    image: apache/airflow:2.9.3
    container_name: nyb_airflow_webserver
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      _PIP_ADDITIONAL_REQUIREMENTS: pandas sqlalchemy psycopg2-binary python-dotenv requests
      MTA_API_KEY: ${MTA_API_KEY}
    volumes:
      - ./:/opt/airflow
    ports:
      - "8181:8080"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.9.3
    container_name: nyb_airflow_scheduler
    depends_on:
      airflow-webserver:
        condition: service_started
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      _PIP_ADDITIONAL_REQUIREMENTS: pandas sqlalchemy psycopg2-binary python-dotenv requests
      MTA_API_KEY: ${MTA_API_KEY}
    volumes:
      - ./:/opt/airflow
    command: scheduler

volumes:
  postgres_db:
